# Generated by Django 6.0.3 on 2026-05-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_social_and_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='card_display_name',
            field=models.CharField(blank=True, help_text='Shown as @name on the video card (optional).', max_length=150),
        ),
        migrations.AddField(
            model_name='video',
            name='card_logo',
            field=models.ImageField(blank=True, help_text='Profile image for this video in the feed.', null=True, upload_to='video_logos/'),
        ),
    ]
