# Generated by Django 6.0.3 on 2026-05-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='reply_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the reply was sent', null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='reply_text',
            field=models.TextField(blank=True, help_text='Admin reply to this contact message', null=True),
        ),
    ]
